//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JamesThewDOTcom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContestResult
    {
        public int CustomerID { get; set; }
        public Nullable<int> Score { get; set; }
        public Nullable<int> RegisterContestID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual RegiterContest RegiterContest { get; set; }
    }
}
