//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JamesThewDOTcom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegiterContest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RegiterContest()
        {
            this.ContestResults = new HashSet<ContestResult>();
            this.CustomerRecipes = new HashSet<CustomerRecipe>();
        }
    
        public int RegisterContestID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> CookingContestID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContestResult> ContestResults { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual CookingContest CookingContest { get; set; }
        public virtual CookingContest CookingContest1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerRecipe> CustomerRecipes { get; set; }
    }
}
