//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testentity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerType()
        {
            this.CustomerType_CookingContest = new HashSet<CustomerType_CookingContest>();
            this.CustomerType_CookingContest1 = new HashSet<CustomerType_CookingContest>();
            this.CustomerType_CookingContest2 = new HashSet<CustomerType_CookingContest>();
            this.ExamRegistrations = new HashSet<ExamRegistration>();
            this.ExamRegistrations1 = new HashSet<ExamRegistration>();
            this.ExamRegistrations2 = new HashSet<ExamRegistration>();
            this.RecipeType_CustomerType = new HashSet<RecipeType_CustomerType>();
            this.RecipeType_CustomerType1 = new HashSet<RecipeType_CustomerType>();
            this.RecipeType_CustomerType2 = new HashSet<RecipeType_CustomerType>();
        }
    
        public int CustomersTypeID { get; set; }
        public string CustomersTypeName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerType_CookingContest> CustomerType_CookingContest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerType_CookingContest> CustomerType_CookingContest1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerType_CookingContest> CustomerType_CookingContest2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExamRegistration> ExamRegistrations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExamRegistration> ExamRegistrations1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExamRegistration> ExamRegistrations2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecipeType_CustomerType> RecipeType_CustomerType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecipeType_CustomerType> RecipeType_CustomerType1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecipeType_CustomerType> RecipeType_CustomerType2 { get; set; }
    }
}
