//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testentity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerType_CookingContest
    {
        public int CustomersTypeID { get; set; }
        public string Title { get; set; }
    
        public virtual CookingContest CookingContest { get; set; }
        public virtual CookingContest CookingContest1 { get; set; }
        public virtual CookingContest CookingContest2 { get; set; }
        public virtual CustomerType CustomerType { get; set; }
        public virtual CustomerType CustomerType1 { get; set; }
        public virtual CustomerType CustomerType2 { get; set; }
    }
}
