//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testentity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees_Group
    {
        public int EmployeeID { get; set; }
        public int GroupID { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual Employee Employee2 { get; set; }
        public virtual Group Group { get; set; }
        public virtual Group Group1 { get; set; }
        public virtual Group Group2 { get; set; }
    }
}
