//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testentity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamRegistration
    {
        public int ID { get; set; }
        public string NameExamRegistration { get; set; }
        public string Email { get; set; }
        public string AddressExamRegistration { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<int> CustomersTypeID { get; set; }
        public Nullable<int> PaymentTypeID { get; set; }
    
        public virtual CustomerType CustomerType { get; set; }
        public virtual CustomerType CustomerType1 { get; set; }
        public virtual CustomerType CustomerType2 { get; set; }
        public virtual PaymentType PaymentType { get; set; }
        public virtual PaymentType PaymentType1 { get; set; }
        public virtual PaymentType PaymentType2 { get; set; }
    }
}
