//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testentity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecipeType_CustomerType
    {
        public int RecipeTypeID { get; set; }
        public int CustomersTypeID { get; set; }
    
        public virtual CustomerType CustomerType { get; set; }
        public virtual CustomerType CustomerType1 { get; set; }
        public virtual CustomerType CustomerType2 { get; set; }
        public virtual RecipeType RecipeType { get; set; }
        public virtual RecipeType RecipeType1 { get; set; }
        public virtual RecipeType RecipeType2 { get; set; }
    }
}
